export const GPUBufferUsage = {
  COPY_SRC: 4,
  COPY_DST: 8,
  INDEX: 16,
  INDIRECT: 256,
  MAP_READ: 1,
  MAP_WRITE: 2,
  QUERY_RESOLVE: 512,
  STORAGE: 128,
  UNIFORM: 64,
  VERTEX: 32,
};

export const GPUTextureUsage = {
  COPY_SRC: 1,
  COPY_DST: 2,
  RENDER_ATTACHMENT: 16,
  STORAGE_BINDING: 8,
  TEXTURE_BINDING: 4,
};
